language: node_js
node_js:
  - node
notifications:
  email:
    recipients:
      - chaos@xuyuanxiang.cn
    on_success: never
    on_failure: always
jobs:
  include:
    - stage: test
      branches:
        only:
          - master
          - "/^v\\d{1}\\.\\d{1,2}.\\d{1,2}$/"
      script:
        - npm test
        - npm install codecov -g
      after_success:
        - codecov
    - stage: npm release
      script:
        - echo "Deploying to npm ..."
        - npm run compile
      branches:
        only:
          - "/^v\\d{1}\\.\\d{1,2}.\\d{1,2}$/"
      deploy:
        provider: npm
        email: chaos@xuyuanxiang.cn
        on:
          tags: true
          repo: xuyuanxiang/react-hooks-pull-to-refresh
        api_key:
          secure: Fst6lMF/5PQg6e5VIcF1AXGVuTm40boG0YK4z1sIy+bRvGkIC41cBh8ZBdr7SX8ukFEwAOR1TfvhFI5fu/EuZadPSfWcgYqZQaXjJXMAB5u/EvvzD13BIpARFFbjNxJa0nBLAYbtRIzadqaZ+OmY5NvXiCVW7Aqb6Ix+UttAiK0l/8wasVMugyprzGJb3bXfGgCNe3PlS+4qf4LoPXW/oJjIwqmYbpeZz5WlRNWHNearXgVtkMmAZMQZV/WST28KehM8zeYw/BJ8cJWasZYs6f73gPLm63vfi9tkNm9xqRK8tUZLor2gR83EJf792Q1Z0jyYYoX2YWKd/SadIPE6UbqkYdpUBmprviyPxnBMIiaZTbblqIXYmsJVqjDfWtuKr5LkNwElwp9bVyD71MVVkVp98LdIDRtBPNllZ8ns7Dcd4XLDrL/SIaJdoMMA50z9GGP2JY9k9rTpLgG3P/IqiQvlRJx83N9RjE1YNIbAPmI5+f1RxUGmuHYG/SjF23NXmwjtO1bC+oFja+LozrS1sIoxlrhlw1aDfpZl84M9DFtaJalhQxRLk6/Zojb0/ReI0R26RZqBLM3RFLQ4naNtM6z/Bp27tloNqFQIwau0iBkVUOKqRvMiW67lU4HYbwu6AT55KPF6+HMpv6kNbK9XxnmKlpC2nHDUWhrlrENaDCk=
    - stage: pages release
      branches:
        only:
          - "/^v\\d{1}\\.\\d{1,2}.\\d{1,2}$/"
      script:
        - echo "Deploying to github pages ..."
        - npm run gen
        - npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        email: chaos@xuyuanxiang.cn
        github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: public
        on:
          tags: true
          repo: xuyuanxiang/react-hooks-pull-to-refresh
